```{r,echo=FALSE,message=FALSE,warning=FALSE}
r3dDefaults = rgl::r3dDefaults
m = structure(c(0.921, -0.146, 0.362, 0, 0.386, 0.482, -0.787, 0, 
                -0.06, 0.864, 0.5, 0, 0, 0, 0, 1), .Dim = c(4L, 4L))
r3dDefaults$FOV = 50
r3dDefaults$userMatrix = m
r3dDefaults$zoom = 0.75

knitr::opts_chunk$set(
  comment =  "#>", 
  collapse = TRUE,
  fig.align = "center")

options(crayon.enabled = TRUE)
rgl::setupKnitr(autoprint = TRUE)
old_hooks <- fansi::set_knit_hooks(knitr::knit_hooks, which = c("output", "message", "error"))
```

# Getting Started with R {#sec-getting-started-with-r}

## Installing R and RStudio {#sec-installing-r-and-rstudio}

`ALSroads` is an R package and requires an installation of the R programming language that can be downloaded for [Windows](https://cran.r-project.org/bin/windows/base/), [macOS](https://cran.r-project.org/bin/macosx/), and [Linux](https://cran.r-project.org/).

The R language is usually used using an integrated development environment (IDE). RStudio is the most famous IDE for R and is available for [download online](https://www.rstudio.com/products/rstudio/download/).

Several tutorials detailing the initial setup and introduction to R are available online:

1.  [An Introduction to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)
2.  [Introduction to Data Science](http://rafalab.dfci.harvard.edu/dsbook/)
3.  [R Tutorial: a quick beginner's guide to using R](https://www.educative.io/blog/r-tutorial-beginners-guide?utm_campaign=systemdesign&utm_source=google&utm_medium=ppc&utm_content=display&eid=5082902844932096&utm_term=&utm_campaign=%5BNew%5D+System+Design+-Performance+Max&utm_source=adwords&utm_medium=ppc&hsa_acc=5451446008&hsa_cam=18511913007&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gclid=CjwKCAjwwL6aBhBlEiwADycBINYGVe6DKs-ltrHhcWCaXn2YWOLIzaS1M162W2r50WPD-xekqnBDNRoCxDYQAvD_BwE)
4.  [R Packages: A Beginner's Tutorial](https://www.datacamp.com/tutorial/r-packages-guide?utm_source=google&utm_medium=paid_search&utm_campaignid=12492439676&utm_adgroupid=122563405841&utm_device=c&utm_keyword=load%20package%20r&utm_matchtype=b&utm_network=g&utm_adpostion=&utm_creative=628195624215&utm_targetid=kwd-341542417371&utm_loc_interest_ms=&utm_loc_physical_ms=9001561&utm_campaign=220808_1-sea~field~data-sci_2-b2c_3-tier1_4-prc_5-na_6-na_7-le_8-pdsh-go_9-na_10-na_11-na-atvr&gclid=CjwKCAjwwL6aBhBlEiwADycBII7QlkF0V6g49x7msm6NWxiQzTbOMTKE1rX4W_zj_VGpOcNRrALxNBoCVFUQAvD_BwE)

## Installing `ALSroads` {#sec-installing-alsroad}

`ALSroads` is available on [Github](https://github.com/Jean-Romain/ALSroads) but is not part of the available packages on CRAN. To install `ALSroads`, you must first install the package `remotes` and then use `remotes` to install the `ALSroads` package from Github.

```r
install.packages("remotes")
remotes::install_github("Jean-Romain/ALSroads")
```